from dataclasses import dataclass
from datetime import datetime, timedelta

import requests

API_BASE = "https://api.notion.com/v1"
# 2025-09-03 split "databases" and "data sources" apart: a database can now
# hold more than one data source (each with its own pages), and pages are
# only reachable by querying a specific data source, not the database
# directly. This pipeline used to be pinned to the older 2022-06-28
# version, querying /v1/databases/{id}/query directly — real
# CologneCurators tickets were going missing from the master list because
# of this (confirmed: a legitimately-submitted, verified-to-exist code
# wasn't among the pulled results, and its database has a data source ID
# distinct from the database ID). See NotionClient.query_task_records for
# how a database_id now gets resolved to its data source(s) before
# anything is queried.
NOTION_VERSION = "2025-09-03"

# Task codes are generated by a Notion formula shaped like:
#   "<2-letter prefix>" + prop("ID") + formatDate(prop("Created time"), "YYMMDDHHmm") + upper(substring(prop("Brand"), 0, 4))
# With no separators between parts, the embedded creation date has to be
# pulled back out from the end. The trailing brand abbreviation is NOT a
# fixed length in practice (e.g. "COLOC" for CologneCurators is 5
# characters, not the 4 the formula's substring() suggests some brand
# names produce) — so the suffix is however many alphabetic characters
# trail the code, whatever that length is, and the date/time is always
# exactly the 10 digits before that.
_CODE_DATE_LEN = 10


def _split_code(code):
    """Splits a code's body (everything after the 2-letter prefix) into
    (id_part, date_block, suffix). Returns (body, None, None) for a legacy
    all-digit code with no brand suffix — there's no reliable place to draw
    the id/date boundary without one."""
    body = code[2:]
    i = len(body)
    while i > 0 and body[i - 1].isalpha():
        i -= 1
    if i == len(body) or i < _CODE_DATE_LEN:
        return body, None, None
    return body[: i - _CODE_DATE_LEN], body[i - _CODE_DATE_LEN : i], body[i:]


def code_created_date(code):
    """Returns a datetime derived from a Notion-generated code's embedded
    creation timestamp, or None if the code doesn't fit that shape (e.g. a
    legacy-scheme code, which has no alphabetic brand suffix at all)."""
    _, date_block, _ = _split_code(code)
    if date_block is None or not date_block.isdigit():
        return None
    try:
        return datetime.strptime(date_block, "%y%m%d%H%M")
    except ValueError:
        return None


# Real-world codes for the same ticket have been observed differing in
# their embedded date/time between what Notion's API returns and what a
# person sees typing the same code from Notion's own UI — by exactly 1
# hour for a contractor in Nigeria, and by much more for contractors in
# the Philippines/Vietnam. That points to Notion rendering the formula's
# date in whichever timezone the viewing person/session is in, not a
# contractor typo (the rest of the code — prefix, ID, brand suffix — still
# matches exactly every time). Rather than track each contractor's
# timezone by hand (fragile if they travel, and more config to maintain),
# a gap is accepted as the same code if it lines up with an actual
# whole-hour timezone difference — real-world UTC offsets are (almost)
# always whole hours, so genuine timezone drift lands within a few minutes
# of an hour mark, while an unrelated code wouldn't coincidentally line up
# that precisely. _MAX_TIMEZONE_SPREAD caps it at the widest gap that
# exists between any two real timezones on Earth, so a wildly-wrong code
# can't slip through just because its minutes-past-the-hour happened to
# align.
_HOUR_MARK_SLACK = timedelta(minutes=5)
_MAX_TIMEZONE_SPREAD = timedelta(hours=15)


def codes_match(submitted_code, notion_code):
    """True if a code submitted on Upwork and a code pulled from Notion
    refer to the same ticket: exact match on prefix, ID, and brand suffix,
    and an embedded date/time gap that lines up with a whole-hour timezone
    difference (see above) rather than requiring it byte-identical. Legacy
    all-digit codes (no brand suffix to anchor a split on) fall back to a
    plain exact match, since there's no reliable id/date boundary to
    compare piecewise."""
    if submitted_code[:2].upper() != notion_code[:2].upper():
        return False
    sub_id, sub_date, sub_suffix = _split_code(submitted_code)
    notion_id, notion_date, notion_suffix = _split_code(notion_code)
    if sub_date is None or notion_date is None:
        return submitted_code == notion_code
    if sub_id != notion_id or sub_suffix != notion_suffix:
        return False
    try:
        sub_dt = datetime.strptime(sub_date, "%y%m%d%H%M")
        notion_dt = datetime.strptime(notion_date, "%y%m%d%H%M")
    except ValueError:
        return submitted_code == notion_code
    diff = abs(sub_dt - notion_dt)
    if diff > _MAX_TIMEZONE_SPREAD:
        return False
    distance_from_hour_mark = min(diff % timedelta(hours=1), timedelta(hours=1) - diff % timedelta(hours=1))
    return distance_from_hour_mark <= _HOUR_MARK_SLACK


def find_matching_code(submitted_code, notion_codes):
    """Returns whichever code in notion_codes matches submitted_code (see
    codes_match), or None. notion_codes should be small enough (per-pod
    master list, not the whole workspace) that a linear scan is fine."""
    for notion_code in notion_codes:
        if codes_match(submitted_code, notion_code):
            return notion_code
    return None


def drop_codes_before(records, cutoff_date):
    """records: a list of NotionTaskRecord. cutoff_date: an ISO "YYYY-MM-DD"
    string (a pod's ignore_codes_before), or falsy to skip filtering
    entirely. Returns (kept_records, dropped_count) — a record whose
    creation date can't be determined is kept rather than guessed away.
    Shared by main.py (real runs) and scripts/demo.py (fixtures)."""
    if not cutoff_date:
        return records, 0
    cutoff = datetime.strptime(cutoff_date, "%Y-%m-%d")
    kept = [r for r in records if (code_created_date(r.task_code) or cutoff) >= cutoff]
    return kept, len(records) - len(kept)


@dataclass
class NotionTaskRecord:
    task_code: str


class NotionError(RuntimeError):
    pass


class NotionClient:
    def __init__(self, token):
        self.token = token

    def _headers(self):
        return {
            "Authorization": f"Bearer {self.token}",
            "Notion-Version": NOTION_VERSION,
            "Content-Type": "application/json",
        }

    def _get_data_source_ids(self, database_id):
        resp = requests.get(f"{API_BASE}/databases/{database_id}", headers=self._headers())
        if not resp.ok:
            raise NotionError(f"Notion database lookup failed for {database_id} ({resp.status_code}): {resp.text}")
        return [ds["id"] for ds in resp.json().get("data_sources", [])]

    def _query_data_source_pages(self, data_source_id):
        pages = []
        cursor = None
        while True:
            body = {"start_cursor": cursor} if cursor else {}
            resp = requests.post(f"{API_BASE}/data_sources/{data_source_id}/query", headers=self._headers(), json=body)
            if not resp.ok:
                raise NotionError(
                    f"Notion query failed for data source {data_source_id} ({resp.status_code}): {resp.text}"
                )

            data = resp.json()
            pages.extend(data["results"])
            if not data.get("has_more"):
                break
            cursor = data["next_cursor"]
        return pages

    def query_task_records(self, database_id, property_map):
        """property_map maps our field names to this database's actual
        Notion property names, since schemas vary per brand — see
        pods.yaml. There's no per-contractor assignment in Notion: a code
        is just a ticket that any pod member can legitimately submit once
        each (see ledger.py for how "once each" is tracked). task_code is
        the full code Notion generated for that ticket (e.g.
        "TB11426081516482608251636"), pulled verbatim — together, every
        record from every brand a pod covers is that pod's master list.

        A database can span multiple data sources (see NOTION_VERSION's
        comment) — every page in every one of them is included, config
        only needs the database_id, not each data source's own ID."""
        records = []
        for data_source_id in self._get_data_source_ids(database_id):
            for page in self._query_data_source_pages(data_source_id):
                props = page["properties"]
                # Notion codes are generated uppercase (see the formula in
                # the module docstring above) — normalizing here means a
                # contractor's Upwork memo only has to match case-insensitively
                # (upwork_csv.py normalizes the same way) rather than needing
                # byte-for-byte case to line up for an "exact match".
                task_code = _extract_text(props.get(property_map["task_code"])).strip().upper()
                if not task_code:
                    print(
                        f"  Warning: page {page.get('id')} has a blank Task Code "
                        f"(check the '{property_map['task_code']}' property name/formula on this database)"
                    )
                    continue
                records.append(NotionTaskRecord(task_code=task_code))
        return records


def _extract_text(prop):
    if not prop:
        return ""
    prop_type = prop.get("type")
    if prop_type == "title":
        return "".join(t["plain_text"] for t in prop["title"])
    if prop_type == "rich_text":
        return "".join(t["plain_text"] for t in prop["rich_text"])
    if prop_type == "select":
        return (prop.get("select") or {}).get("name", "")
    if prop_type == "people":
        people = prop.get("people") or []
        return people[0]["name"] if people else ""
    if prop_type == "formula":
        # Task codes are generated by a Notion formula property — its result
        # is nested one level deeper, under whichever result type the
        # formula actually produces.
        formula = prop.get("formula") or {}
        formula_type = formula.get("type")
        if formula_type == "string":
            return formula.get("string") or ""
        if formula_type == "number":
            number = formula.get("number")
            return str(number) if number is not None else ""
        if formula_type == "boolean":
            return str(formula.get("boolean"))
        if formula_type == "date":
            date = formula.get("date")
            return date["start"] if date else ""
        return ""
    return ""
